filebeat:
  prospectors:
    - paths:
        - /var/log/syslog
        - /var/log/*/*.log
        - /var/snap/microstack/common/log
        - /var/snap/microstack/common/log/mysql
        - /var/snap/microstack/common/log/openvswitch
        - /var/snap/microstack/common/log/rabbitmq

      input_type: log
      exclude_files: ["/filebeat.*", ".*gz$"]
      exclude_lines: []
      scan_frequency: 10s
      harvester_buffer_size: 16384
      max_bytes: 10485760

  registry_file: filebeat/registry

logging:
  to_syslog: true
  to_files: false
  level: info
  metrics.enabled: false
  files:
    path: /var/snap/microstack/common/log
    name: filebeat
    keepfiles: 7
    permissions: 0644
